#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python /app/manage.py collectstatic --noinput
uvicorn config.asgi:application --host 0.0.0.0 --port 5000 --reload --log-level trace --access-log
