#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

uvicorn config.asgi:application --host 0.0.0.0 --port 5000 --reload --log-level debug --access-log /app/access.log --error-log /app/error.log
