[package]
name = "exp_viz"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "exp_viz"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
cov_viz_ds = { git = "https://github.com/ReddyLab/cov_viz_ds", rev = "e3a4b84903d23bdbc7e4f88fd24c6e5f6a91aa11" }
pyo3 = { version = "0.17.1", features = ["extension-module"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
