[package]
name = "exp_viz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "exp_viz"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
pyo3 = { version = "0.16.3", features = ["extension-module"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
rustc-hash = "1.1.0"
