# Generated by Django 3.2.6 on 2021-09-01 21:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geneassembly',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='search_geneassembly_loc_index'),
        ),
    ]
