# Generated by Django 4.0.3 on 2022-05-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnaregion",
            name="closest_gene",
        ),
        migrations.RemoveField(
            model_name="gencodeannotation",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="gencodeannotation",
            name="feature_assembly",
        ),
        migrations.RemoveField(
            model_name="regulatoryeffect",
            name="targets",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
