# Generated by Django 3.2.6 on 2021-09-24 13:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaseihypersensitivesite',
            name='closest_gene_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.geneassembly'),
        ),
    ]
