# Generated by Django 3.2.6 on 2021-09-24 13:11

from django.db import migrations


def add_assembly(apps, _schema_editor):
    # We can't import the DNaseIHypersensitiveSite model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DNaseIHypersensitiveSite = apps.get_model('search', 'DNaseIHypersensitiveSite')
    for dhs in DNaseIHypersensitiveSite.objects.all():
        dhs.closest_gene_assembly = dhs.closest_gene.assemblies.get(ref_genome=dhs.ref_genome, ref_genome_patch=dhs.ref_genome_patch)
        dhs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_dnaseihypersensitivesite_closest_gene_assembly'),
    ]

    operations = [
        migrations.RunPython(add_assembly)
    ]
