# Generated by Django 4.0.3 on 2022-05-10 17:29

import cegs_portal.search.models.accession
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_remove_dnaregion_closest_gene_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="regulatoryeffect",
            name="regulatoryeffect_srchbl_idx",
        ),
        migrations.AddField(
            model_name="dnaregion",
            name="accession_id",
            field=models.CharField(
                max_length=12,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.accession.validate_accession_id],
            ),
        ),
        migrations.AddField(
            model_name="featureassembly",
            name="accession_id",
            field=models.CharField(
                max_length=12,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.accession.validate_accession_id],
            ),
        ),
        migrations.AddField(
            model_name="regulatoryeffect",
            name="accession_id",
            field=models.CharField(
                max_length=12,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.accession.validate_accession_id],
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="accession_id",
            field=models.CharField(
                max_length=12,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.accession.validate_accession_id],
            ),
        ),
    ]
