# Generated by Django 3.2.6 on 2021-09-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_geneassembly_search_geneassembly_loc_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneassembly',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.gene'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='assemblies',
            field=models.ManyToManyField(related_name='gene_set', to='search.GeneAssembly'),
        ),
    ]
