# Generated by Django 3.2.6 on 2021-09-02 17:11

from django.db import migrations

from cegs_portal.search.models import GeneAssembly

def set_gene(_apps, _schema_editor):
    for assembly in GeneAssembly.objects.all():
        gene = assembly.gene_set.first()
        assembly.gene = gene
        assembly.save()

class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210902_1125'),
    ]

    operations = [
        migrations.RunPython(set_gene),
    ]
