# Generated by Django 3.2.6 on 2021-09-29 18:53

import cegs_portal.search.models.reg_effects
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_add_gene_assembly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='RegulatoryEffect',
            old_name='score',
            new_name='effect_size',
        ),
        migrations.AddField(
            model_name='RegulatoryEffect',
            name='raw_p_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='RegulatoryEffect',
            name='target_assemblies',
            field=models.ManyToManyField(related_name='regulatory_effects', to='search.GeneAssembly'),
        ),
        migrations.AlterField(
            model_name='RegulatoryEffect',
            name='direction',
            field=models.CharField(choices=[(cegs_portal.search.models.reg_effects.EffectDirectionType['DEPLETED'], 'depleted'), (cegs_portal.search.models.reg_effects.EffectDirectionType['ENRICHED'], 'enriched'), (cegs_portal.search.models.reg_effects.EffectDirectionType['BOTH'], 'both'), (cegs_portal.search.models.reg_effects.EffectDirectionType['NON_SIGNIFICANT'], 'non_sig')], default=cegs_portal.search.models.reg_effects.EffectDirectionType['NON_SIGNIFICANT'], max_length=8),
        ),
        migrations.CreateModel(
            name='ExperimentDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_line', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=512)),
                ('ref_genome', models.CharField(max_length=20)),
                ('ref_genome_patch', models.CharField(max_length=10)),
                ('significance_measure', models.CharField(max_length=2048)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='Experiment',
            name='data_files',
            field=models.ManyToManyField(related_name='experiment_set', to='search.ExperimentDataFile'),
        ),
    ]
