# Generated by Django 3.2.6 on 2021-09-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210902_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneassembly',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.gene'),
        ),
    ]
