# Generated by Django 3.2.6 on 2021-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210929_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnaseihypersensitivesite',
            name='strand',
        ),
        migrations.AddField(
            model_name='dnaseihypersensitivesite',
            name='screen_accession_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dnaseihypersensitivesite',
            name='cell_line',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
