# Generated by Django 4.0.3 on 2022-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_dnafeature_dnafeature_sdf_name_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnafeature',
            name='closest_gene_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dnafeature',
            name='closest_gene_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
