# Generated by Django 3.2.6 on 2021-09-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210930_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='dnaseihypersensitivesite',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.file'),
        ),
    ]
