# Generated by Django 4.0.3 on 2022-07-26 20:04

import cegs_portal.search.models.dna_feature
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_dnafeature_closest_gene_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnafeature',
            name='feature_type',
            field=models.CharField(choices=[(cegs_portal.search.models.dna_feature.DNAFeatureType['GENE'], 'gene'), (cegs_portal.search.models.dna_feature.DNAFeatureType['TRANSCRIPT'], 'transcript'), (cegs_portal.search.models.dna_feature.DNAFeatureType['EXON'], 'exon'), (cegs_portal.search.models.dna_feature.DNAFeatureType['CCRE'], 'ccre'), (cegs_portal.search.models.dna_feature.DNAFeatureType['DHS'], 'dhs'), (cegs_portal.search.models.dna_feature.DNAFeatureType['GRNA'], 'gRNA')], default=cegs_portal.search.models.dna_feature.DNAFeatureType['GENE'], max_length=50),
        ),
    ]
