# Generated by Django 4.0.3 on 2022-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_alter_dnafeature_feature_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulatoryeffect",
            name="sources",
            field=models.ManyToManyField(related_name="source_for", to="search.dnafeature"),
        ),
        migrations.AlterField(
            model_name="regulatoryeffect",
            name="target_assemblies",
            field=models.ManyToManyField(related_name="target_of", to="search.dnafeature"),
        ),
    ]
