# Generated by Django 3.2.6 on 2021-10-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20211007_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exonassembly',
            name='exon',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='assemblies',
        ),
        migrations.RemoveField(
            model_name='geneassembly',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='assemblies',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='transcriptassembly',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='gencodeannotation',
            name='exon',
        ),
        migrations.RemoveField(
            model_name='gencodeannotation',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='gencodeannotation',
            name='transcript',
        ),
        migrations.AlterField(
            model_name='dnaseihypersensitivesite',
            name='closest_gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.feature'),
        ),
        migrations.AlterField(
            model_name='dnaseihypersensitivesite',
            name='closest_gene_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.featureassembly'),
        ),
        migrations.AlterField(
            model_name='regulatoryeffect',
            name='target_assemblies',
            field=models.ManyToManyField(related_name='regulatory_effects', to='search.FeatureAssembly'),
        ),
        migrations.AlterField(
            model_name='regulatoryeffect',
            name='targets',
            field=models.ManyToManyField(related_name='regulatory_effects', to='search.Feature'),
        ),
        migrations.DeleteModel(
            name='Exon',
        ),
        migrations.DeleteModel(
            name='ExonAssembly',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='GeneAssembly',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
        migrations.DeleteModel(
            name='TranscriptAssembly',
        ),
    ]
