# Generated by Django 3.2.6 on 2021-10-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20211012_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='data_files',
        ),
        migrations.AddField(
            model_name='experiment',
            name='other_files',
            field=models.ManyToManyField(related_name='experiments', to='search.File'),
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='search.experiment'),
        ),
    ]
