# Generated by Django 4.0.3 on 2022-08-12 15:44

import cegs_portal.search.models.dna_feature
import cegs_portal.search.models.facets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_dnafeature_closest_gene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureassembly',
            name='parent',
        ),
        migrations.AlterField(
            model_name='dnafeature',
            name='feature_type',
            field=models.CharField(choices=[('DNAFeatureType.GENE', 'gene'), ('DNAFeatureType.TRANSCRIPT', 'transcript'), ('DNAFeatureType.EXON', 'exon'), ('DNAFeatureType.CCRE', 'ccre'), ('DNAFeatureType.DHS', 'dhs'), ('DNAFeatureType.GRNA', 'gRNA')], default=cegs_portal.search.models.dna_feature.DNAFeatureType['GENE'], max_length=50),
        ),
        migrations.AlterField(
            model_name='facet',
            name='facet_type',
            field=models.CharField(choices=[('FacetType.DISCRETE', 'Discrete'), ('FacetType.CONTINUOUS', 'Continuous')], default=cegs_portal.search.models.facets.FacetType['CONTINUOUS'], max_length=30),
        ),
        migrations.DeleteModel(
            name='DNARegion',
        ),
        migrations.DeleteModel(
            name='FeatureAssembly',
        ),
    ]
