# Generated by Django 3.2.6 on 2021-10-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20211014_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaseihypersensitivesite',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureassembly',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulatoryeffect',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='regulatoryeffect',
            index=models.Index(fields=['searchable'], name='regulatoryeffect_srchbl_idx'),
        ),
    ]
