# Generated by Django 4.0.3 on 2022-08-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_remove_featureassembly_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulatoryeffect',
            old_name='target_assemblies',
            new_name='targets',
        ),
    ]
