# Generated by Django 4.1 on 2022-08-15 18:03

import cegs_portal.search.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0011_rename_target_assemblies_regulatoryeffect_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnafeature",
            name="accession_id",
            field=models.CharField(
                max_length=15,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.validators.validate_accession_id],
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="accession_id",
            field=models.CharField(
                max_length=15,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.validators.validate_accession_id],
            ),
        ),
        migrations.AlterField(
            model_name="regulatoryeffect",
            name="accession_id",
            field=models.CharField(
                max_length=15,
                null=True,
                unique=True,
                validators=[cegs_portal.search.models.validators.validate_accession_id],
            ),
        ),
    ]
