# Generated by Django 3.2.6 on 2021-10-14 18:32

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20211014_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DNaseIHypersensitiveSite',
            new_name='DNARegion'
        ),
        migrations.AddField(
            model_name='DNARegion',
            name='misc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dnaregion',
            name='region_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='regulatoryeffect',
            name='sources',
            field=models.ManyToManyField(related_name='regulatory_effects', to='search.DNARegion'),
        ),
        migrations.AddIndex(
            model_name='dnaregion',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='search_region_location_index'),
        ),
        migrations.RemoveIndex(
            model_name='dnaregion',
            name="search_dhs_location_index"
        ),
        migrations.RemoveField(
            model_name='dnaregion',
            name='screen_accession_id',
        ),
    ]
