# Generated by Django 4.1 on 2022-08-22 13:55

import cegs_portal.search.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0012_alter_dnafeature_accession_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnafeature",
            name="accession_id",
            field=models.CharField(
                max_length=15, unique=True, validators=[cegs_portal.search.models.validators.validate_accession_id]
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="accession_id",
            field=models.CharField(
                max_length=15, unique=True, validators=[cegs_portal.search.models.validators.validate_accession_id]
            ),
        ),
        migrations.AlterField(
            model_name="regulatoryeffect",
            name="accession_id",
            field=models.CharField(
                max_length=15, unique=True, validators=[cegs_portal.search.models.validators.validate_accession_id]
            ),
        ),
        migrations.AddIndex(
            model_name="dnafeature",
            index=models.Index(fields=["accession_id"], name="sdf_accession_id_index"),
        ),
        migrations.AddIndex(
            model_name="regulatoryeffect",
            index=models.Index(fields=["accession_id"], name="re_accession_id_index"),
        ),
    ]
