# Generated by Django 3.2.6 on 2021-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20211014_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaregion',
            name='strand',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
