# Generated by Django 4.1 on 2022-08-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_alter_dnafeature_accession_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RegulatoryEffect",
            new_name="RegulatoryEffectObservation",
        ),
    ]
