# Generated by Django 3.2.6 on 2021-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_featureassembly_feature_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='featureassembly',
            index=models.Index(fields=['feature_type'], name='sfa_feature_type_index'),
        ),
    ]
