# Generated by Django 4.1 on 2022-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_rename_regulatoryeffect_regulatoryeffectobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facetvalue",
            name="value",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
