# Generated by Django 4.1 on 2022-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_alter_facetvalue_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnafeature",
            name="closest_gene_ensembl_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
