# Generated by Django 3.2.9 on 2021-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_featureassembly_sfa_feature_type_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
