# Generated by Django 3.2.9 on 2021-11-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20211118_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='search.facet')),
            ],
        ),
        migrations.AddIndex(
            model_name='facetvalue',
            index=models.Index(fields=['value'], name='sfv_value_index'),
        ),
    ]
