# Generated by Django 3.2.9 on 2021-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20211118_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaregion',
            name='facet_values',
            field=models.ManyToManyField(to='search.FacetValue'),
        ),
        migrations.AddField(
            model_name='regulatoryeffect',
            name='facet_values',
            field=models.ManyToManyField(to='search.FacetValue'),
        ),
    ]
