# Generated by Django 4.1 on 2022-10-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0017_auto_20221004_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulatoryeffectobservation",
            name="experiment_accession_id",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
