# Generated by Django 4.1 on 2022-10-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0018_regulatoryeffectobservation_chroms_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE search_regulatoryeffectobservation SET experiment_accession_id =
            (SELECT sexper.accession_id
	         FROM search_experiment as sexper
             WHERE sexper.id = search_regulatoryeffectobservation.experiment_id)""",
            reverse_sql="UPDATE search_regulatoryeffectobservation SET experiment_accession_id = null",
        ),
    ]
