# Generated by Django 4.1 on 2022-10-12 19:25

import cegs_portal.search.models.dna_feature
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0019_auto_20221011_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnafeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("DNAFeatureType.GENE", "gene"),
                    ("DNAFeatureType.TRANSCRIPT", "transcript"),
                    ("DNAFeatureType.EXON", "exon"),
                    ("DNAFeatureType.CCRE", "ccre"),
                    ("DNAFeatureType.DHS", "dhs"),
                    ("DNAFeatureType.GRNA", "gRNA"),
                    ("DNAFeatureType.CAR", "chromatin accessable region"),
                ],
                default=cegs_portal.search.models.dna_feature.DNAFeatureType["GENE"],
                max_length=50,
            ),
        ),
    ]
