# Generated by Django 3.2.9 on 2021-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_experiment_facet_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='facet_values',
            field=models.ManyToManyField(to='search.FacetValue'),
        ),
    ]
