# Generated by Django 3.2.9 on 2021-12-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_file_facet_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TissueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='cell_lines',
            field=models.ManyToManyField(related_name='experiment_data', to='search.CellLine'),
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='tissue_types',
            field=models.ManyToManyField(related_name='experiment_data', to='search.TissueType'),
        ),
    ]
