# Generated by Django 4.1 on 2022-10-21 15:38

import cegs_portal.search.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0020_alter_dnafeature_feature_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessionIdLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField()),
                (
                    "accession_type",
                    models.CharField(
                        choices=[
                            ("AccessionType.GENE", "gene"),
                            ("AccessionType.TRANSCRIPT", "transcript"),
                            ("AccessionType.EXON", "exon"),
                            ("AccessionType.REGULATORY_EFFECT_OBS", "regulatory effect observation"),
                            ("AccessionType.GRNA", "grna"),
                            ("AccessionType.CCRE", "ccre"),
                            ("AccessionType.DHS", "dhs"),
                            ("AccessionType.EXPERIMENT", "experiment"),
                            ("AccessionType.CAR", "chromatin accessable region"),
                            ("AccessionType.TT", "tissue type"),
                            ("AccessionType.CL", "cell line"),
                            ("AccessionType.BIOS", "biosample"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "accession_id",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[cegs_portal.search.models.validators.validate_accession_id],
                    ),
                ),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name="accessionidlog",
            index=models.Index(fields=["accession_type"], name="sal_type_index"),
        ),
        migrations.AddIndex(
            model_name="accessionidlog",
            index=models.Index(fields=["created_at"], name="sal_created_index"),
        ),
    ]
