# Generated by Django 4.1 on 2022-10-26 17:30

import cegs_portal.search.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0021_accessionidlog_accessionidlog_sal_type_index_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cellline",
            old_name="line_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tissuetype",
            old_name="tissue_type",
            new_name="name",
        ),
        migrations.AddField(
            model_name="cellline",
            name="accession_id",
            field=models.CharField(
                default="DCPCL00000000",
                max_length=15,
                unique=True,
                validators=[cegs_portal.search.models.validators.validate_accession_id],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cellline",
            name="description",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="cellline",
            name="tissue_type",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to="search.tissuetype"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cellline",
            name="tissue_type_name",
            field=models.CharField(default="Tissue", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tissuetype",
            name="accession_id",
            field=models.CharField(
                default="DCPTT00000000",
                max_length=15,
                unique=True,
                validators=[cegs_portal.search.models.validators.validate_accession_id],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tissuetype",
            name="description",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.CreateModel(
            name="Biosample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "accession_id",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[cegs_portal.search.models.validators.validate_accession_id],
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("cell_line_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=4096, null=True)),
                ("misc", models.JSONField(null=True)),
                ("cell_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="search.cellline")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="biosamples",
            field=models.ManyToManyField(related_name="experiments", to="search.biosample"),
        ),
    ]
