# Generated by Django 4.0.1 on 2022-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20211206_1509'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dnaregion',
            index=models.Index(fields=['searchable'], name='dnaregion_srchbl_idx'),
        ),
        migrations.AddIndex(
            model_name='featureassembly',
            index=models.Index(fields=['searchable'], name='featureassembly_srchbl_idx'),
        ),
    ]
