# Generated by Django 4.0.1 on 2022-03-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_facet_facet_type_facetvalue_num_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryeffect',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='regulatoryeffect',
            name='effect_size',
        ),
        migrations.RemoveField(
            model_name='regulatoryeffect',
            name='raw_p_value',
        ),
        migrations.RemoveField(
            model_name='regulatoryeffect',
            name='significance',
        ),
    ]
