# Generated by Django 4.0.3 on 2022-04-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_experiment_accession_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnaregion',
            old_name='chromosome_name',
            new_name='chrom_name',
        ),
    ]
