# Generated by Django 4.0.3 on 2022-04-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_rename_chromosome_name_dnaregion_chrom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureassembly',
            name='ensembl_id',
            field=models.CharField(default='No ID', max_length=50),
        ),
        migrations.AddField(
            model_name='featureassembly',
            name='feature_subtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='featureassembly',
            name='misc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='featureassembly',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='search.featureassembly'),
        ),
    ]
