# Generated by Django 4.1.3 on 2022-12-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0027_alter_biosample_description_alter_biosample_misc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnafeature",
            name="parent_accession",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_accession_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_accession",
                to="search.dnafeature",
                to_field="accession_id",
            ),
        ),
    ]
