# Generated by Django 4.0.3 on 2022-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_featureassembly_ensembl_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencodeannotation',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
