# Generated by Django 4.1.5 on 2023-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0027_alter_biosample_description_alter_biosample_misc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdatafile",
            name="ref_genome_patch",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
