# Generated by Django 4.1.3 on 2022-12-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0028_dnafeature_parent_accession"),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE search_dnafeature as sdf1 SET parent_accession_id =
            (SELECT pdf.accession_id
            FROM search_dnafeature as pdf
            WHERE sdf1.parent_id = pdf.id)""",
            reverse_sql="UPDATE search_dnafeature SET parent_accession_id = null",
        )
    ]
