# Generated by Django 4.0.3 on 2022-04-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_gencodeannotation_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencodeannotation',
            name='feature_assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation', to='search.featureassembly'),
        ),
    ]
