# Generated by Django 4.0.3 on 2022-04-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_gencodeannotation_feature_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureassembly',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='search.feature'),
        ),
    ]
