# Generated by Django 4.1.5 on 2023-01-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0029_auto_20221215_1437"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="all_locations",
        ),
        migrations.RemoveField(
            model_name="vcfentry",
            name="file",
        ),
        migrations.RemoveField(
            model_name="vcfentry",
            name="variant",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Variant",
        ),
        migrations.DeleteModel(
            name="VariantLocation",
        ),
        migrations.DeleteModel(
            name="VCFEntry",
        ),
        migrations.DeleteModel(
            name="VCFFile",
        ),
    ]
