# Generated by Django 4.1.5 on 2023-02-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0028_alter_experimentdatafile_ref_genome_patch"),
        ("search", "0030_remove_variant_all_locations_remove_vcfentry_file_and_more"),
    ]

    operations = []
