# Generated by Django 4.0.3 on 2022-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_alter_featureassembly_feature'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='featureassembly',
            index=models.Index(fields=['ensembl_id'], name='sfa_ensembl_id_index'),
        ),
    ]
