# Generated by Django 4.0.3 on 2022-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_featureassembly_sfa_ensembl_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnaregion',
            name='facet_num_values',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='facet_num_values',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='facet_num_values',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='regulatoryeffect',
            name='facet_num_values',
            field=models.JSONField(null=True),
        ),
    ]
