# Generated by Django 4.0.3 on 2022-04-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_dnaregion_facet_num_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetvalue',
            name='num_value',
        ),
    ]
