# Generated by Django 4.1.6 on 2023-02-27 20:13

from django.db import migrations


def unmigrate_files(apps, schema_editor):
    Experiment = apps.get_model("search", "Experiment")
    ExperimentDataFileInfo = apps.get_model("search", "ExperimentDataFileInfo")

    for file_info in ExperimentDataFileInfo.objects.prefetch_related("file").all():
        files = file_info.file.all()
        file_info.delete()
        for file in files:
            file.delete()

    for experiment in Experiment.objects.prefetch_related("other_files").all():
        for file in experiment.other_files.all():
            file.experiment = None
            file.save()


def migrate_files(apps, schema_editor):
    Experiment = apps.get_model("search", "Experiment")
    File = apps.get_model("search", "File")
    ExperimentDataFileInfo = apps.get_model("search", "ExperimentDataFileInfo")

    for experiment in Experiment.objects.prefetch_related("data_files", "other_files").all():
        for file in experiment.other_files.all():
            file.experiment = experiment
            file.save()

        for file in experiment.data_files.all():
            data_file_info = ExperimentDataFileInfo(
                ref_genome=file.ref_genome,
                ref_genome_patch=file.ref_genome_patch,
                significance_measure=file.significance_measure,
            )
            data_file_info.save()
            new_file = File(
                filename=file.filename,
                description=file.description,
                experiment=experiment,
                data_file_info=data_file_info,
            )
            new_file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0032_experimentdatafileinfo_filecategory_file_experiment_and_more"),
    ]

    operations = [migrations.RunPython(migrate_files, unmigrate_files)]
