# Generated by Django 4.1.6 on 2023-03-20 15:56

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0034_alter_experimentdatafileinfo_p_value_threshold_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dnafeature",
            index=models.Index(django.db.models.functions.text.Upper("name"), name="sdf_name_insensitive_index"),
        ),
    ]
