# Generated by Django 4.1.6 on 2023-03-28 18:04

from django.db import migrations, transaction

from cegs_portal.search.models import AccessionIds, AccessionType


def migrate_analyses(apps, schema_editor):
    Experiment = apps.get_model("search", "Experiment")
    Analysis = apps.get_model("search", "Analysis")

    experiments = Experiment.objects.all()

    with AccessionIds(message="Migrating Analyses (0042_auto_20230328_1404)") as accession_ids:
        with transaction.atomic():
            for experiment in experiments:
                for file in experiment.files.all():
                    if file.data_file_info is not None:
                        analysis = Analysis(
                            accession_id=accession_ids.incr(AccessionType.ANALYSIS), experiment=experiment
                        )
                        analysis.save()
                        file.analysis = analysis
                        file.save()


# This isn't a perfect "unmigration". ANALYSIS accession ids don't get
# decremented. This means that every time this migration is run the Analysis
# Accession IDs will be higher that the last time it was run.
def unmigrate_analyses(apps, schema_editor):
    Analysis = apps.get_model("search", "Analysis")

    for analysis in Analysis.objects.all():
        analysis.delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("search", "0036_pipeline_alter_file_url_analysis_file_analysis_squashed_0041_alter_analysis_experiment"),
    ]

    operations = [migrations.RunPython(migrate_analyses, unmigrate_analyses)]
