# Generated by Django 4.1.6 on 2023-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0043_alter_analysis_options_dnafeature_analysis_accession_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(fields=["accession_id"], name="an_accession_id_index"),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(fields=["accession_id"], name="exp_accession_id_index"),
        ),
    ]
