# Generated by Django 4.1.6 on 2023-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0044_analysis_an_accession_id_index_and_more"),
    ]

    operations = [
        # Set the analysis accession id to the analysis associated with the experiment that
        # produced the REO.
        migrations.RunSQL(
            """UPDATE search_regulatoryeffectobservation AS sreo SET analysis_accession_id =
            (SELECT sa.accession_id
            FROM search_experiment as sexper
            JOIN search_analysis as sa ON sexper.accession_id = sa.experiment_accession_id
            WHERE sreo.experiment_accession_id = sexper.accession_id LIMIT 1)""",
            reverse_sql="UPDATE search_regulatoryeffectobservation SET analysis_accession_id = null",
        ),
    ]
