# Generated by Django 4.1.6 on 2023-04-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0045_auto_20230328_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="search.analysis",
            ),
        ),
    ]
