# Generated by Django 4.1.6 on 2023-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0046_alter_file_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="name",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
