# Generated by Django 4.1.6 on 2023-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0047_analysis_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="misc",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
