# Generated by Django 4.2 on 2023-06-23 15:45

import cegs_portal.search.models.facets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0050_experiment_default_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facet",
            name="facet_type",
            field=models.CharField(
                choices=[("FacetType.CATEGORICAL", "Categorical"), ("FacetType.NUMERIC", "Numeric")],
                default=cegs_portal.search.models.facets.FacetType["NUMERIC"],
                max_length=30,
            ),
        ),
        migrations.RunSQL(
            """UPDATE search_facet AS sf SET facet_type = 'FacetType.CATEGORICAL'
            WHERE facet_type = 'FacetType.DISCRETE'""",
            reverse_sql="""UPDATE search_facet AS sf SET facet_type = 'FacetType.DISCRETE'
            WHERE facet_type = 'FacetType.CATEGORICAL'""",
        ),
        migrations.RunSQL(
            """UPDATE search_facet AS sf SET facet_type = 'FacetType.NUMERIC'
            WHERE facet_type = 'FacetType.CONTINUOUS'""",
            reverse_sql="""UPDATE search_facet AS sf SET facet_type = 'FacetType.CONTINUOUS'
            WHERE facet_type = 'FacetType.NUMERIC'""",
        ),
    ]
