# Generated by Django 4.1.6 on 2023-07-12 20:12

import cegs_portal.search.models.dna_feature_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0051_alter_facet_facet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnafeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("DNAFeatureType.GENE", "Gene"),
                    ("DNAFeatureType.TRANSCRIPT", "Transcript"),
                    ("DNAFeatureType.EXON", "Exon"),
                    ("DNAFeatureType.CCRE", "cCRE"),
                    ("DNAFeatureType.DHS", "DHS"),
                    ("DNAFeatureType.GRNA", "gRNA"),
                    ("DNAFeatureType.CAR", "Chromatin Accessable Region"),
                ],
                default=cegs_portal.search.models.dna_feature_type.DNAFeatureType["GENE"],
                max_length=50,
            ),
        ),
    ]
