# Generated by Django 4.2.3 on 2023-07-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0052_alter_dnafeature_feature_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dnafeature",
            old_name="source",
            new_name="source_file",
        ),
    ]
