# Generated by Django 4.2.3 on 2023-10-05 18:10

import cegs_portal.search.models.dna_feature_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0053_rename_source_dnafeature_source_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessionidlog",
            name="accession_type",
            field=models.CharField(
                choices=[
                    ("AccessionType.GENE", "gene"),
                    ("AccessionType.TRANSCRIPT", "transcript"),
                    ("AccessionType.EXON", "exon"),
                    ("AccessionType.REGULATORY_EFFECT_OBS", "regulatory effect observation"),
                    ("AccessionType.GRNA", "grna"),
                    ("AccessionType.CCRE", "ccre"),
                    ("AccessionType.DHS", "dhs"),
                    ("AccessionType.EXPERIMENT", "experiment"),
                    ("AccessionType.CAR", "chromatin accessible region"),
                    ("AccessionType.TT", "tissue type"),
                    ("AccessionType.CL", "cell line"),
                    ("AccessionType.BIOS", "biosample"),
                    ("AccessionType.ANALYSIS", "analysis"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dnafeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("DNAFeatureType.GENE", "Gene"),
                    ("DNAFeatureType.TRANSCRIPT", "Transcript"),
                    ("DNAFeatureType.EXON", "Exon"),
                    ("DNAFeatureType.CCRE", "cCRE"),
                    ("DNAFeatureType.DHS", "DHS"),
                    ("DNAFeatureType.GRNA", "gRNA"),
                    ("DNAFeatureType.CAR", "Chromatin Accessible Region"),
                ],
                default=cegs_portal.search.models.dna_feature_type.DNAFeatureType["GENE"],
                max_length=50,
            ),
        ),
    ]
