# Generated by Django 4.2.3 on 2023-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0055_alter_accessionidlog_accession_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnafeature",
            name="associated_ccres",
            field=models.ManyToManyField(blank=True, related_name="associated_sources", to="search.dnafeature"),
        ),
    ]
