# Generated by Django 4.2.3 on 2023-11-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0056_dnafeature_associated_ccres"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gencodeannotation",
            name="search_gen_anno_type_index",
        ),
    ]
