# Generated by Django 4.2.7 on 2024-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0057_remove_gencodeannotation_search_gen_anno_type_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdatafileinfo",
            name="significance_measure",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
