# Generated by Django 4.2.11 on 2024-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0058_alter_experimentdatafileinfo_significance_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdatafileinfo",
            name="p_value_adj_method",
            field=models.CharField(default="unknown", max_length=128),
        ),
        migrations.AddField(
            model_name="file",
            name="location",
            field=models.CharField(default="unknown", max_length=2048),
            preserve_default=False,
        ),
    ]
