# Generated by Django 4.2.11 on 2024-04-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0059_experimentdatafileinfo_p_value_adj_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="p_value_adj_method",
            field=models.CharField(default="unknown", max_length=128),
        ),
        migrations.AddField(
            model_name="analysis",
            name="p_value_threshold",
            field=models.FloatField(blank=True, default=0.05),
        ),
        migrations.AddField(
            model_name="analysis",
            name="ref_genome",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="analysis",
            name="ref_genome_patch",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="dnafeature",
            name="associated_ccres",
            field=models.ManyToManyField(blank=True, to="search.dnafeature"),
        ),
        migrations.AlterField(
            model_name="file",
            name="data_file_info",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="file", to="search.analysis"
            ),
        ),
        migrations.AddIndex(
            model_name="gencodeannotation",
            index=models.Index(fields=["annotation_type"], name="search_gen_anno_type_index"),
        ),
        migrations.DeleteModel(
            name="ExperimentDataFileInfo",
        ),
    ]
