# Generated by Django 4.2.11 on 2024-04-24 16:26

from django.db import migrations, models
import django.db.models.deletion


def unmigrate_file_data(apps, schema_editor):
    Analysis = apps.get_model("search", "Analysis")
    ExperimentDataFileInfo = apps.get_model("search", "ExperimentDataFileInfo")

    for analysis in Analysis.objects.all():
        file = analysis.files.first()
        file.data_file_info = ExperimentDataFileInfo(
            ref_genome=analysis.genome_assembly,
            ref_genome_patch=analysis.genome_assembly_patch,
            p_value_threshold=analysis.p_value_threshold,
            p_value_adj_method=analysis.p_value_adj_method,
        )
        file.data_file_info.save()
        file.save()


def migrate_file_data(apps, schema_editor):
    ExperimentDataFileInfo = apps.get_model("search", "ExperimentDataFileInfo")

    for file_info in ExperimentDataFileInfo.objects.all():
        analysis = file_info.file.first().analysis
        analysis.genome_assembly = file_info.ref_genome
        analysis.genome_assembly_patch = file_info.ref_genome_patch
        analysis.p_value_threshold = file_info.p_value_threshold
        analysis.p_value_adj_method = file_info.p_value_adj_method
        analysis.save()


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0059_experimentdatafileinfo_p_value_adj_method_and_more"),
        ("get_expr_data", "0018_auto_20231114_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="p_value_adj_method",
            field=models.CharField(default="unknown", max_length=128),
        ),
        migrations.AddField(
            model_name="analysis",
            name="p_value_threshold",
            field=models.FloatField(blank=True, default=0.05),
        ),
        migrations.AddField(
            model_name="analysis",
            name="genome_assembly",
            field=models.CharField(max_length=20, default="GRCh38"),
        ),
        migrations.AddField(
            model_name="analysis",
            name="genome_assembly_patch",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="dnafeature",
            name="associated_ccres",
            field=models.ManyToManyField(blank=True, to="search.dnafeature"),
        ),
        migrations.RunPython(migrate_file_data, unmigrate_file_data),
        migrations.RemoveField(
            model_name="file",
            name="data_file_info",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="file", to="search.analysis"
            ),
        ),
        migrations.AddIndex(
            model_name="gencodeannotation",
            index=models.Index(fields=["annotation_type"], name="search_gen_anno_type_index"),
        ),
        migrations.DeleteModel(
            name="ExperimentDataFileInfo",
        ),
    ]
