# Generated by Django 5.1 on 2024-10-04 14:44

from django.db import migrations
from cegs_portal.search.migrations.utils.facets import change_facet

OLD_FACET = "CRISPR Modulation"
NEW_FACET = "Functional Characterization Modality"

NEW_DESCRIPTION = "Functional Characterization Method"
OLD_DESCRIPTION = "CRISPR modulation method"


def update_facet(apps, schema_editor):
    Facet = apps.get_model("search", "Facet")
    change_facet(Facet, OLD_FACET, new_facet_name=NEW_FACET, new_facet_description=NEW_DESCRIPTION)


def revert_facet(apps, schema_editor):
    Facet = apps.get_model("search", "Facet")
    change_facet(Facet, NEW_FACET, new_facet_name=OLD_FACET, new_facet_description=OLD_DESCRIPTION)


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0064_auto_20240924_1004"),
    ]

    operations = [
        migrations.RunPython(update_facet, revert_facet),
    ]
