# Generated by Django 5.1.2 on 2024-10-29 20:51

from django.db import connection, migrations


def update_closest_gene_distance(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE search_dnafeature as sdf
           	SET closest_gene_distance = ((upper(sdf.location) + lower(sdf.location)) / 2) - upper(genes.location)
           	FROM search_dnafeature as genes
           	WHERE sdf.closest_gene_id is not null AND sdf.closest_gene_id = genes.id AND genes.strand = '-';
           	"""
        )
        cursor.execute(
            """
            UPDATE search_dnafeature as sdf
           	SET closest_gene_distance = ((upper(sdf.location) + lower(sdf.location)) / 2) - lower(genes.location)
           	FROM search_dnafeature as genes
           	WHERE sdf.closest_gene_id is not null AND sdf.closest_gene_id = genes.id AND genes.strand = '+';
           	"""
        )


def revert_closest_gene_distance(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE search_dnafeature
            SET closest_gene_distance = abs(closest_gene_distance)
            WHERE closest_gene_id is not null;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0065_auto_20241004_1044"),
    ]

    operations = [migrations.RunPython(update_closest_gene_distance, revert_closest_gene_distance)]
