# Generated by Django 5.1.2 on 2024-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0067_alter_analysis_genome_assembly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnafeature",
            name="significant_reo",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            UPDATE search_dnafeature SET significant_reo = TRUE WHERE search_dnafeature.id IN (SELECT "search_dnafeature"."id"
            FROM "search_dnafeature"
              LEFT OUTER JOIN "search_regulatoryeffectobservation_sources" ON ("search_dnafeature"."id" = "search_regulatoryeffectobservation_sources"."dnafeature_id")
              LEFT OUTER JOIN "search_regulatoryeffectobservation" ON ("search_regulatoryeffectobservation_sources"."regulatoryeffectobservation_id" = "search_regulatoryeffectobservation"."id")
              LEFT OUTER JOIN "search_regulatoryeffectobservation_facet_values" ON ("search_regulatoryeffectobservation"."id" = "search_regulatoryeffectobservation_facet_values"."regulatoryeffectobservation_id")
              LEFT OUTER JOIN "search_facetvalue" ON ("search_regulatoryeffectobservation_facet_values"."facetvalue_id" = "search_facetvalue"."id")
            WHERE "search_facetvalue"."value" IN ('Depleted Only', 'Enriched Only', 'Mixed')
            GROUP BY search_dnafeature.id)
            """,
            """
            UPDATE search_dnafeature SET significant_reo = FALSE WHERE significant_reo = TRUE
            """,
        ),
    ]
