# Generated by Django 5.1.2 on 2024-11-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0069_auto_20241111_1334"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pi", models.CharField(max_length=512)),
                ("institution", models.CharField(max_length=512)),
                ("experimentalist", models.CharField(blank=True, max_length=512)),
                ("project", models.CharField(blank=True, max_length=512)),
                ("datasource_url", models.URLField(blank=True)),
                ("lab_url", models.URLField(blank=True)),
                (
                    "experiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attribution", to="search.experiment"
                    ),
                ),
            ],
        ),
    ]
