# Generated by Django 5.1.4 on 2025-02-06 19:34

import cegs_portal.search.models.dna_feature_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0072_experimentrelation_experiment_related_experiments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnafeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("DNAFeatureType.GENE", "Gene"),
                    ("DNAFeatureType.TRANSCRIPT", "Transcript"),
                    ("DNAFeatureType.EXON", "Exon"),
                    ("DNAFeatureType.CCRE", "cCRE"),
                    ("DNAFeatureType.DHS", "DHS"),
                    ("DNAFeatureType.GRNA", "gRNA"),
                    ("DNAFeatureType.CAR", "Chromatin Accessible Region"),
                    ("DNAFeatureType.CRE", "Called Regulatory Element"),
                    ("DNAFeatureType.GE", "Genomic Element"),
                ],
                default=cegs_portal.search.models.dna_feature_type.DNAFeatureType["GENE"],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CCRE", "cCRE"),
                    ("DHS", "DHS"),
                    ("GRNA", "gRNA"),
                    ("CAR", "Chromatin Accessible Region"),
                    ("CRE", "Called Regulatory Element"),
                    ("GE", "Genomic Element"),
                ],
                default="GRNA",
                max_length=50,
            ),
        ),
    ]
