#!/bin/sh
set -euo pipefail

OUTPUT_DIR=$1

python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"1\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"2\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"3\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"4\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"5\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"6\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"7\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"8\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"9\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"10\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"11\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"12\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"13\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"14\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"15\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"16\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"17\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"18\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"19\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"20\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"21\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"22\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"X\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"Y\")"
python manage.py shell -c "from scripts import gen_chromo_viz_level2; gen_chromo_viz_level2.run(\"$OUTPUT_DIR\", \"MT\")"
