version: '3'
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test_password
volumes:
  pg_data:
