# Generated by Django 4.1.5 on 2023-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_expr_data", "0002_auto_20230117_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReoSourcesTargets",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "reo_sources_targets",
                "managed": False,
            },
        ),
    ]
