# Generated by Django 4.1.5 on 2023-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("get_expr_data", "0003_reosourcestargets"),
    ]

    operations = [
        migrations.RunSQL("DROP MATERIALIZED VIEW IF EXISTS reo_sources_targets", ""),
        migrations.RunSQL(
            """CREATE MATERIALIZED VIEW reo_sources_targets AS
                SELECT sr.id AS reo_id,
                    sr.accession_id AS reo_accession,
                    sr.experiment_accession_id AS reo_experiment,
                    sr.facet_num_values AS reo_facets,
                    sds.id AS source_id,
                    sds.accession_id AS source_accession,
                    sds.chrom_name AS source_chrom,
                    sds.location AS source_loc,
                    sdt.id AS target_id,
                    sdt.accession_id AS target_accession,
                    sdt.chrom_name AS target_chrom,
                    sdt.location AS target_loc,
                    sdt.name AS target_gene_symbol,
                    sdt.ensembl_id AS target_ensembl_id
                FROM search_regulatoryeffectobservation AS sr
                LEFT JOIN search_regulatoryeffectobservation_sources AS srs ON sr.id = srs.regulatoryeffectobservation_id
                LEFT JOIN search_regulatoryeffectobservation_targets AS srt ON sr.id = srt.regulatoryeffectobservation_id
                LEFT JOIN search_dnafeature AS sds ON sds.id = srs.dnafeature_id
                LEFT JOIN search_dnafeature AS sdt ON sdt.id = srt.dnafeature_id""",
            "DROP MATERIALIZED VIEW reo_sources_targets",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_reo_accession ON reo_sources_targets (reo_accession)",
            "DROP INDEX idx_rst_reo_accession",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_reo_experiment ON reo_sources_targets (reo_experiment)",
            "DROP INDEX idx_rst_reo_experiment",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_source_chrom ON reo_sources_targets (source_chrom)", "DROP INDEX idx_rst_source_chrom"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_source_loc ON reo_sources_targets USING GIST (source_loc)",
            "DROP INDEX idx_rst_source_loc",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_srs_target_chrom ON reo_sources_targets (target_chrom)", "DROP INDEX idx_srs_target_chrom"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_srs_target_loc ON reo_sources_targets USING GIST (target_loc)",
            "DROP INDEX idx_srs_target_loc",
        ),
    ]
