# Generated by Django 4.2 on 2023-04-20 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("get_expr_data", "0005_auto_20230418_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
