# Generated by Django 4.2 on 2023-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_expr_data", "0007_remove_experimentdata_data_experimentdata_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdata",
            name="file",
            field=models.FilePathField(
                max_length=512, path="/Users/tc325/Documents/ccgr_portal/portal/cegs_portal/media/expr_data_dir"
            ),
        ),
    ]
