# Generated by Django 4.2 on 2023-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_expr_data", "0008_alter_experimentdata_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdata",
            name="filename",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
