# Generated by Django 4.2 on 2023-06-30 16:37

import cegs_portal.get_expr_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_expr_data", "0014_auto_20230626_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdata",
            name="file",
            field=models.FilePathField(max_length=512, path=cegs_portal.get_expr_data.models.expr_data_base_path),
        ),
    ]
