# Generated by Django 4.2.3 on 2023-11-13 16:22

from django.db import migrations
from cegs_portal.get_expr_data.models import ReoSourcesTargets, ReoSourcesTargetsSigOnly


def refresh_materialized_views(apps, schema_editor):
    ReoSourcesTargets.refresh_view()
    ReoSourcesTargetsSigOnly.refresh_view()


class Migration(migrations.Migration):
    dependencies = [
        ("get_expr_data", "0016_auto_20230703_1604"),
        ("search", "0055_alter_accessionidlog_accession_id_and_more"),
    ]

    operations = [migrations.RunPython(refresh_materialized_views, refresh_materialized_views)]
