# Generated by Django 4.2.11 on 2024-05-07 18:23

from django.db import migrations


REO_SOURCES_TARGETS = """CREATE MATERIALIZED VIEW reo_sources_targets AS
                SELECT sr.id AS reo_id,
                    sr.archived as archived,
                    sr.public as public,
                    sr.accession_id AS reo_accession,
                    sr.experiment_accession_id AS reo_experiment,
                    sr.analysis_accession_id AS reo_analysis,
                    sr.facet_num_values AS reo_facets,
                    sds.id AS source_id,
                    sds.accession_id AS source_accession,
                    sds.chrom_name AS source_chrom,
                    sds.location AS source_loc,
                    sdt.id AS target_id,
                    sdt.accession_id AS target_accession,
                    sdt.chrom_name AS target_chrom,
                    sdt.location AS target_loc,
                    sdt.name AS target_gene_symbol,
                    sdt.ensembl_id AS target_ensembl_id,
                    sa.genome_assembly AS genome_assembly,
                    array_remove(ARRAY_AGG(DISTINCT(srfv.facetvalue_id)) || ARRAY_AGG(DISTINCT(sdsfv.facetvalue_id)) || ARRAY_AGG(DISTINCT(sdtfv.facetvalue_id)), NULL) AS cat_facets
                FROM search_regulatoryeffectobservation AS sr
                LEFT JOIN search_regulatoryeffectobservation_facet_values as srfv on sr.id = srfv.regulatoryeffectobservation_id
                LEFT JOIN search_regulatoryeffectobservation_sources AS srs ON sr.id = srs.regulatoryeffectobservation_id
                LEFT JOIN search_regulatoryeffectobservation_targets AS srt ON sr.id = srt.regulatoryeffectobservation_id
                LEFT JOIN search_dnafeature AS sds ON sds.id = srs.dnafeature_id
                LEFT JOIN search_dnafeature_facet_values as sdsfv on sds.id = sdsfv.dnafeature_id
                LEFT JOIN search_dnafeature AS sdt ON sdt.id = srt.dnafeature_id
                LEFT JOIN search_dnafeature_facet_values as sdtfv on sdt.id = sdtfv.dnafeature_id
                LEFT JOIN search_analysis AS sa ON sr.analysis_accession_id = sa.accession_id
                LEFT JOIN search_file AS sf ON sa.id = sf.analysis_id
                GROUP BY sr.id, sds.id, sdt.id, sa.genome_assembly
                """

REO_SOURCES_TARGETS_SIG_ONLY = """CREATE MATERIALIZED VIEW reo_sources_targets_sig_only AS
                SELECT sr.id AS reo_id,
                    sr.archived as archived,
                    sr.public as public,
                    sr.accession_id AS reo_accession,
                    sr.experiment_accession_id AS reo_experiment,
                    sr.analysis_accession_id AS reo_analysis,
                    sr.facet_num_values AS reo_facets,
                    sds.id AS source_id,
                    sds.accession_id AS source_accession,
                    sds.chrom_name AS source_chrom,
                    sds.location AS source_loc,
                    sdt.id AS target_id,
                    sdt.accession_id AS target_accession,
                    sdt.chrom_name AS target_chrom,
                    sdt.location AS target_loc,
                    sdt.name AS target_gene_symbol,
                    sdt.ensembl_id AS target_ensembl_id,
                    sa.genome_assembly AS genome_assembly,
                    array_remove(ARRAY_AGG(DISTINCT(srfv.facetvalue_id)) || ARRAY_AGG(DISTINCT(sdsfv.facetvalue_id)) || ARRAY_AGG(DISTINCT(sdtfv.facetvalue_id)), NULL) AS cat_facets
                FROM search_regulatoryeffectobservation AS sr
                LEFT JOIN search_regulatoryeffectobservation_facet_values as srfv on sr.id = srfv.regulatoryeffectobservation_id
                LEFT JOIN search_regulatoryeffectobservation_sources AS srs ON sr.id = srs.regulatoryeffectobservation_id
                LEFT JOIN search_regulatoryeffectobservation_targets AS srt ON sr.id = srt.regulatoryeffectobservation_id
                LEFT JOIN search_dnafeature AS sds ON sds.id = srs.dnafeature_id
                LEFT JOIN search_dnafeature_facet_values as sdsfv on sds.id = sdsfv.dnafeature_id
                LEFT JOIN search_dnafeature AS sdt ON sdt.id = srt.dnafeature_id
                LEFT JOIN search_dnafeature_facet_values as sdtfv on sdt.id = sdtfv.dnafeature_id
                LEFT JOIN search_analysis AS sa ON sr.analysis_accession_id = sa.accession_id
                LEFT JOIN search_file AS sf ON sa.id = sf.analysis_id
                WHERE srfv.facetvalue_id != (SELECT id FROM search_facetvalue where value = 'Non-significant')
                GROUP BY sr.id, sds.id, sdt.id, sa.genome_assembly
                """


class Migration(migrations.Migration):
    dependencies = [
        ("get_expr_data", "0018_auto_20231114_1447"),
        ("search", "0060_analysis_p_value_adj_method_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            REO_SOURCES_TARGETS_SIG_ONLY, "DROP MATERIALIZED VIEW IF EXISTS reo_sources_targets_sig_only"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rstso_reo_accession ON reo_sources_targets_sig_only (reo_accession)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rstso_source_loc ON reo_sources_targets_sig_only USING GIST (source_loc)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rstso_target_loc ON reo_sources_targets_sig_only USING GIST (target_loc)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rstso_cat_facet ON reo_sources_targets_sig_only USING GIN (cat_facets)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rstso_pval_asc ON reo_sources_targets_sig_only (((reo_facets->>'Raw p value')::numeric) ASC)",
            "",
        ),
        migrations.RunSQL(
            "ANALYZE reo_sources_targets_sig_only",
            "",
        ),
        migrations.RunSQL(REO_SOURCES_TARGETS, "DROP MATERIALIZED VIEW IF EXISTS reo_sources_targets"),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_reo_accession ON reo_sources_targets (reo_accession)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_source_loc ON reo_sources_targets USING GIST (source_loc)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_target_loc ON reo_sources_targets USING GIST (target_loc)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_cat_facet ON reo_sources_targets USING GIN (cat_facets)",
            "",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rst_pval_asc ON reo_sources_targets (((reo_facets->>'Raw p value')::numeric) ASC)",
            "",
        ),
        migrations.RunSQL(
            "ANALYZE reo_sources_targets",
            "",
        ),
    ]
