# Generated by Django 5.1 on 2024-08-20 20:02

from django.db import migrations


def update_genome_assemblies(apps, schema_editor):
    ReoSourcesTargets = apps.get_model("get_expr_data", "ReoSourcesTargets")
    ReoSourcesTargetsSigOnly = apps.get_model("get_expr_data", "ReoSourcesTargetsSigOnly")

    ReoSourcesTargets.objects.filter(genome_assembly="GRCh37").update(genome_assembly="hg19")
    ReoSourcesTargets.objects.filter(genome_assembly="GRCh38").update(genome_assembly="hg38")

    ReoSourcesTargetsSigOnly.objects.filter(genome_assembly="GRCh37").update(genome_assembly="hg19")
    ReoSourcesTargetsSigOnly.objects.filter(genome_assembly="GRCh38").update(genome_assembly="hg38")


def revert_genome_assemblies(apps, schema_editor):
    ReoSourcesTargets = apps.get_model("get_expr_data", "ReoSourcesTargets")
    ReoSourcesTargetsSigOnly = apps.get_model("get_expr_data", "ReoSourcesTargetsSigOnly")

    ReoSourcesTargets.objects.filter(genome_assembly="hg19").update(genome_assembly="GRCh37")
    ReoSourcesTargets.objects.filter(genome_assembly="hg38").update(genome_assembly="GRCh38")

    ReoSourcesTargetsSigOnly.objects.filter(genome_assembly="hg19").update(genome_assembly="GRCh37")
    ReoSourcesTargetsSigOnly.objects.filter(genome_assembly="hg38").update(genome_assembly="GRCh38")


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0062_ga_crispr_ceres_facet_changes"),
        ("get_expr_data", "0021_reosourcestargets_idx_rstm_reo_analysis_and_more"),
    ]

    operations = [
        migrations.RunPython(update_genome_assemblies, revert_genome_assemblies),
    ]
